pip install numpy
pip install matplotlib
pip install openpyxl
pip install xlrd
pip install pandas
pip install nltk
pip install tensorflow
pip install scipy
pip install sklearn
pip install transformers
pip install argparse
